# This play will force a python install on freshly provisioned instances 

- hosts: all
#Determine which user to be used in here
  remote_user: "dseadmin"
  become: true
  become_user: root
  gather_facts: true
  # The below is optional
  # become_method: sudo
  pre_tasks:
  - name: "install python on Debian machines"
    raw: "sudo apt-get -y install python"
    when: ansible_facts['os_family']|lower == "debian"
  
  - name: "Install python on RedHat machines"
    yum:
      name:
        - python27
      state: present
    when: ansible_facts['os_family']|lower == "redhat"