# Package installation related steps

- name: restart-opscenter-package
  #service: name=opscenterd enabled=yes state=restarted
  # serial: 1
  shell: |
    sudo service opscenterd restart
  args:
    warn: false
  when: dse_install_type == 'package'