# Handlers for dse related notifications

- name: restart-dse
  file: path=/opt/datastax/status/RESTART-REQUIRED state=touch owner=cassandra group=cassandra
  when: dse_install_type == 'tarball'

- name: Restart DSE
  shell: |
    sudo service dse restart
  args:
    warn: false
  when: dse_install_type == 'package'

- name: Wait for DSE service to start
  wait_for:
    port: 9042
    timeout: 1200
    host: "{{ ansible_default_ipv4['address'] }}"
  when: dse_install_type == 'package'